# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the Nginx configuration file from the host to the container
COPY ./nginx/default1.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/htpasswd /etc/nginx/.htpasswd

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]